name: VenikCraft
main: ru.venik.optimize.VenikOptimize
version: 1.0.0
api-version: 1.21
authors: ["venik"]
load: STARTUP
description: "VenikCraft — customized for Venik server (MC 1.21.4)"

commands:
  login:
    description: Login to the server
    usage: /<command> <password>
    aliases: [l]
  register:
    description: Register an account password
    usage: /<command> <password>
    permission: venik.optimize.register
  npc:
    description: Manage NPCs
    usage: /npc <create|remove>
    permission: venikoptimize.npc
permissions:
  venik.optimize.register:
    description: Allow registering a password
    default: op
  venikoptimize.npc:
    description: Allow managing NPCs
    default: op
